<div align="center">
  <img src="https://upload.wikimedia.org/wikipedia/commons/3/31/NumPy_logo_2020.svg" alt="لوگو" width="500">
</div>


<div dir='rtl'>

# آموزش کاربردی NUMPY با محوریت علوم داده و محاسبات عددی

## **جلسه اول** مقدمه و آموزش نصب و راه اندازی

### مدت زمان مطالعه  

مدت زمان مورد نیاز برای مطالعه این صفحه **20 تا 30 دقیقه** است. این مدت زمان بسته به سطح آشنایی شما با **Python** و موضوعات مرتبط ممکن است متغیر باشد.  


**تهیه‌کننده:** سجاد چمن‌آرا  

---

</div>

<div dir='rtl'>

### **نصب و راه‌اندازی NumPy در Jupyter Notebook و Google Colab**

#### **۱. نصب NumPy در Jupyter Notebook**
**Jupyter Notebook** یک محیط محبوب برای اجرای **کدهای پایتون** است که از NumPy پشتیبانی می‌کند. برای نصب NumPy در آن:

1️⃣ ابتدا یک **سلول جدید** در Jupyter Notebook باز کنید.

2️⃣ دستور زیر را اجرا کنید:

</div>

In [8]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


<div dir='rtl'>

✅ با اجرای این دستور، **آخرین نسخه NumPy** نصب شده و آماده استفاده خواهد بود.

3️⃣ **تست نصب:** پس از نصب، کد زیر را اجرا کنید تا از صحت نصب NumPy مطمئن شوید:

</div>

In [9]:
import numpy as np
print(np.__version__)

2.3.0


<div dir='rtl'>

📌 این کد نسخه نصب‌شده NumPy را نمایش می‌دهد.

---

</div>

<div dir='rtl'>

#### **۲. استفاده از NumPy در Google Colab**
**Google Colab** نیازی به نصب دستی NumPy ندارد، زیرا به صورت **پیش‌فرض** آن را شامل می‌شود. اما در صورتی که بخواهید نسخه جدیدتری را نصب کنید:

1️⃣ یک سلول جدید در Google Colab ایجاد کنید.

2️⃣ دستور نصب را اجرا کنید:

</div>

In [10]:
!pip install numpy --upgrade

Defaulting to user installation because normal site-packages is not writeable


<div dir='rtl'>

✅ این دستور نسخه جدید NumPy را نصب یا به‌روزرسانی می‌کند.

3️⃣ برای تست اجرا از کد زیر استفاده کنید:


</div>

In [11]:
import numpy as np
print(np.array([1, 2, 3]))

[1 2 3]


<div dir='rtl'>

📌 اگر آرایه `[1, 2, 3]` نمایش داده شد، یعنی **NumPy به درستی نصب شده است.**

---

</div>

<div dir='rtl'>

### **معرفی NumPy و تفاوت آن با لیست‌های معمولی Python**

**NumPy** (Numeric Python) یکی از قدرتمندترین کتابخانه‌های پایتون برای **محاسبات عددی** و پردازش **داده‌های حجیم** است. این کتابخانه پایه‌ی بسیاری از **الگوریتم‌های هوش مصنوعی، پردازش تصویر، داده‌کاوی و یادگیری ماشین** محسوب می‌شود.

---

### **🔹 چرا NumPy؟**
لیست‌های معمولی پایتون (`list`) ساختار پایه‌ای دارند اما در پردازش‌های سنگین با محدودیت‌هایی مواجه می‌شوند:
- **عملکرد ضعیف‌تر:** لیست‌های Python بهینه نیستند و هنگام پردازش داده‌های حجیم، سرعت آنها کاهش می‌یابد.
- **مصرف حافظه بیشتر:** آرایه‌های NumPy مقدار **کمتری** از حافظه نسبت به لیست‌های Python اشغال می‌کنند.
- **توابع علمی و عددی پیشرفته:** NumPy شامل **عملیات ماتریسی، محاسبات برداری، توابع ریاضی و آماری** است که در لیست‌های معمولی Python وجود ندارد.
- **Broadcasting:** قابلیت پردازش **هم‌زمان** مقادیر بدون نیاز به حلقه‌های `for`، که **سرعت اجرای کدها را افزایش** می‌دهد.

---

### **📌 تفاوت NumPy و لیست‌های معمولی Python**

<div dir='ltr'; align='center'>

| ویژگی               | لیست Python | NumPy |
|----------------------|------------|-------|
| **سرعت اجرا**       | کندتر | سریع‌تر (C-based) |
| **مصرف حافظه**      | بیشتر | بهینه‌تر |
| **توابع ریاضی**    | محدود | توابع پیشرفته |
| **Broadcasting** | ندارد | دارد |
| **محاسبات برداری** | ندارد | دارد |
| **استفاده در یادگیری ماشین** | نامناسب | بسیار کاربردی |

</div>

---

### **🔹 مثال عملی**
**➤ لیست Python:**

</div>

In [12]:
lst = [1, 2, 3, 4]
squared_lst = [x**2 for x in lst]
print(squared_lst)

[1, 4, 9, 16]


<div dir='rtl'>

⏳ زمان اجرا: **کندتر** به دلیل استفاده از حلقه `for`.

**➤ NumPy:**

</div>

In [13]:
import numpy as np
arr = np.array([1, 2, 3, 4])
squared_arr = arr**2
print(squared_arr)

[ 1  4  9 16]


<div dir='rtl'>

⚡ زمان اجرا: **بسیار سریع‌تر** به دلیل استفاده از پردازش برداری.

---

</div>

<div dir='rtl'>

### **🔹 بهینه‌سازی عملکرد محاسبات عددی با NumPy**

**NumPy** به دلیل پیاده‌سازی مبتنی بر زبان **C**، عملکرد فوق‌العاده‌ای در پردازش داده‌های **عددی و ماتریسی** دارد. با این حال، برای **بهینه‌سازی محاسبات** و افزایش سرعت اجرا، می‌توان از چندین روش مؤثر استفاده کرد.

---

### **📌 ۱. استفاده از بردارسازی (Vectorization)**
در پایتون، اجرای حلقه‌های `for` باعث کاهش سرعت می‌شود. **NumPy** با پردازش برداری (`vectorization`) این مشکل را حل می‌کند.

✍ **➤ مثال بدون NumPy (کُند):**

</div>

In [14]:
data = [1, 2, 3, 4, 5]
squared_data = [x**2 for x in data]  # اجرای حلقه برای هر مقدار
print(squared_data)

[1, 4, 9, 16, 25]


<div dir='rtl'>

⏳ **کند، زیرا پردازش روی هر مقدار جداگانه انجام می‌شود.**

🚀 **➤ مثال با NumPy (بهینه):**

</div>

In [ ]:
import numpy as np
data = np.array([1, 2, 3, 4, 5])
squared_data = data**2  # محاسبه برداری سریع
print(squared_data)

<div dir='rtl'>

⚡ **سریع‌تر، زیرا تمام عناصر به‌صورت همزمان پردازش می‌شوند.**

---

### **📌 ۲. استفاده از Broadcasting**
**Broadcasting** به NumPy اجازه می‌دهد عملیات ریاضی را بدون نیاز به حلقه روی **چندین آرایه با اندازه‌های متفاوت** اجرا کند.

🚀 **➤ مثال با Broadcasting:**

</div>

In [15]:
import numpy as np
matrix = np.array([[1, 2, 3], [4, 5, 6]])
vector = np.array([1, 2, 3])
result = matrix + vector  # Broadcasting در مقیاس ماتریسی
print(result)

[[2 4 6]
 [5 7 9]]


<div dir='rtl'>

✅ **Broadcasting** باعث اجرای عملیات بدون نیاز به حلقه دستی می‌شود.

---

### **📌 ۳. استفاده از توابع بهینه‌شده NumPy**
توابع داخلی NumPy بسیار سریع‌تر از حلقه‌های معمولی Python هستند. همیشه از توابع آماده‌ی NumPy برای پردازش داده‌ها استفاده کنید.

🔹 **➤ مثال توابع سریع NumPy:**

</div>

In [16]:
import numpy as np
arr = np.random.rand(1000000)  # تولید آرایه تصادفی بزرگ
mean_value = np.mean(arr)  # محاسبه میانگین با عملکرد بهینه
std_dev = np.std(arr)  # محاسبه انحراف معیار

<div dir='rtl'>

💡 **استفاده از توابع NumPy به جای حلقه‌های دستی، پردازش داده را چندین برابر سریع‌تر می‌کند.**

---

### **📌 ۴. استفاده از نوع داده‌های بهینه (`dtype`)**
انتخاب صحیح **نوع داده (`dtype`)** تأثیر مستقیمی بر **سرعت اجرا و مصرف حافظه** دارد.

🔹 **➤ مثال بهینه‌سازی `dtype`:**

</div>

In [17]:
import numpy as np
arr = np.array([1, 2, 3], dtype=np.float32)  # استفاده از float32 بجای float64
print(arr.dtype)  # نمایش نوع داده

float32


<div dir='rtl'>

✅ استفاده از **`float32`** به جای **`float64`** مصرف حافظه را کاهش داده و محاسبات عددی سریع‌تر انجام می‌شود.

---

### **📌 ۵. استفاده از `numexpr` برای پردازش‌های پیچیده**
در پردازش‌های بسیار سنگین، می‌توان از **`numexpr`** که از چندین پردازنده استفاده می‌کند، کمک گرفت.

🔹 **➤ نصب `numexpr`:**

</div>

In [18]:
!pip install numexpr

Defaulting to user installation because normal site-packages is not writeable


<div dir='rtl'>

🔹 **➤ استفاده از `numexpr` برای محاسبات بسیار سریع‌تر:**

</div>

In [19]:
import numpy as np
import numexpr as ne

arr = np.random.rand(1000000)
result = ne.evaluate("arr**2 + 3*arr - 5")  # اجرای عملیات بهینه‌شده

<div dir='rtl'>

⚡ **`numexpr` پردازش‌های پیچیده را چندین برابر سریع‌تر می‌کند.**

</div>