<div align="center">
  <img src="https://upload.wikimedia.org/wikipedia/commons/3/31/NumPy_logo_2020.svg" alt="لوگو" width="500">
</div>


<div dir='rtl'>

# آموزش کاربردی NUMPY با محوریت علوم داده و محاسبات عددی

## **جلسه دوم** آرایه ها و عملیات پایه

### مدت زمان مطالعه  

مدت زمان مورد نیاز برای مطالعه این صفحه **20 تا 30 دقیقه** است. این مدت زمان بسته به سطح آشنایی شما با **Python** و موضوعات مرتبط ممکن است متغیر باشد.  


**تهیه‌کننده:** سجاد چمن‌آرا  

---

</div>

<div dir='rtl'>

### **🔹 آرایه‌ها در NumPy (`ndarray`)**

در **NumPy**، آرایه‌ها (`ndarray`) جایگزینی قدرتمند برای لیست‌های معمولی **Python** هستند که امکان اجرای سریع و بهینه‌ی **محاسبات عددی** را فراهم می‌کنند. 

---
### **📌 ۱. ساخت آرایه‌ی یک‌بعدی (1D Array)**
آرایه‌های **یک‌بعدی** مشابه لیست‌های معمولی پایتون هستند اما قابلیت پردازش عددی سریع‌تری دارند:

</div>

In [2]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])  # آرایه یک‌بعدی
print(arr1)
print(arr1.shape)  # نمایش ابعاد آرایه

[1 2 3 4 5]
(5,)


<div dir='rtl'>

---

### **📌 ۲. ساخت آرایه‌ی دوبعدی (2D Array)**
برای ساخت **ماتریس‌های دو‌بعدی** (ماتریس `m x n`) از آرایه‌های چندسطری استفاده می‌شود:

</div>

In [3]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])  # ماتریس ۲×۳
print(arr2)
print(arr2.shape)  # نمایش ابعاد ماتریس

[[1 2 3]
 [4 5 6]]
(2, 3)


<div dir='rtl'>

📌 تعداد بعدها: `shape = (2, 3)`  

---

### **📌 ۳. ساخت آرایه‌ی چندبعدی (3D Array)**
در NumPy می‌توان آرایه‌های **سه‌بعدی و بالاتر** ایجاد کرد:

</div>

In [4]:
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])  # آرایه ۲×۲×۲
print(arr3)
print(arr3.shape)  # نمایش ابعاد

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


<div dir='rtl'>

📌 تعداد بعدها: `shape = (2, 2, 2)`

---

### **📌 ۴. روش‌های دیگر برای ایجاد آرایه‌ها**
- **ایجاد آرایه با مقدار صفر یا یک:**  

</div>

In [5]:
np.zeros((3, 3))  # ماتریس ۳×۳ شامل صفرها
np.ones((2, 2))  # ماتریس ۲×۲ شامل یک‌ها

array([[1., 1.],
       [1., 1.]])

<div dir='rtl'>

- **ایجاد آرایه با بازه‌ی مشخص:**  

</div>

In [6]:
np.arange(1, 10, 2)  # آرایه با گام ۲ → [1 3 5 7 9]
np.linspace(0, 1, 5)  # آرایه با ۵ مقدار بین ۰ و ۱

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

<div dir='rtl'>

- **ایجاد آرایه تصادفی:**  

</div>

In [7]:
np.random.rand(3, 3)  # ماتریس ۳×۳ با اعداد تصادفی بین ۰ و ۱

array([[0.07189126, 0.99696887, 0.61474566],
       [0.95479458, 0.24258723, 0.81603799],
       [0.25620899, 0.86862976, 0.42783441]])

<div dir='rtl'>

### **🚀 نتیجه‌گیری**
آرایه‌های NumPy قابلیت پردازش **یک‌بعدی، دوبعدی و چندبعدی** را دارند و برای **محاسبات عددی و هوش مصنوعی** بسیار **بهینه** هستند.

---


### **📌 ۱. Indexing (دسترسی به عناصر آرایه)**
برای انتخاب **یک مقدار خاص** از آرایه‌ها می‌توان از **ایندکس‌ها** استفاده کرد.

🔹 **➤ انتخاب مقدار خاص در آرایه یک‌بعدی (1D Array)**:

</div>

In [8]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print(arr[0])  # مقدار اولین عنصر → 10
print(arr[-1]) # مقدار آخرین عنصر → 50

10
50


<div dir='rtl'>

📌 از **ایندکس منفی** (`-1`) برای دسترسی به **آخرین مقدار** استفاده می‌شود.

🔹 **➤ انتخاب مقدار خاص در آرایه دوبعدی (2D Array)**:

</div>

In [9]:
arr2D = np.array([[1, 2, 3], [4, 5, 6]])

print(arr2D[0, 1])  # مقدار ردیف اول، ستون دوم → 2
print(arr2D[1, -1]) # مقدار آخرین ستون در ردیف دوم → 6

2
6


<div dir='rtl'>

📌 فرمت `[row, column]` برای انتخاب مقدار از **ماتریس‌های چندبعدی** استفاده می‌شود.

---

### **📌 ۲. Slicing (بریدن بخش‌هایی از آرایه)**
Slicing برای انتخاب **بخش خاصی** از آرایه‌ها بدون نیاز به حلقه‌های `for` استفاده می‌شود.

🔹 **➤ بریدن آرایه یک‌بعدی:**

</div>

In [10]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[1:4])  # انتخاب عناصر 1 تا 3 → [20 30 40]
print(arr[:3])   # انتخاب 3 مقدار اول → [10 20 30]
print(arr[2:])   # انتخاب از ایندکس ۲ به بعد → [30 40 50]
print(arr[::2])  # انتخاب با گام ۲ → [10 30 50]

[20 30 40]
[10 20 30]
[30 40 50]
[10 30 50]


<div dir='rtl'>

🔹 **➤ بریدن آرایه دوبعدی:**

</div>

In [11]:
arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr2D[:2, 1:])  # انتخاب ۲ ردیف اول و ستون‌های دوم به بعد
print(arr2D[:, 0])    # انتخاب تمام مقادیر **ستون اول**
print(arr2D[1:, :2])  # انتخاب **ردیف‌های ۱ به بعد** و **۲ ستون اول**

[[2 3]
 [5 6]]
[1 4 7]
[[4 5]
 [7 8]]


<div dir='rtl'>

---

### **📌 ۳. انتخاب شرطی با Masking**
با **شرط‌های منطقی** می‌توان مقدارهای خاصی را **فیلتر** کرد.

🔹 **➤ انتخاب مقادیر بزرگتر از ۵:**

</div>

In [12]:
arr = np.array([1, 5, 10, 15, 20])

print(arr[arr > 5])  # انتخاب مقادیر بزرگتر از ۵ → [10 15 20]

[10 15 20]


<div dir='rtl'>

🔹 **➤ فیلتر داده‌های خاص:**

</div>

In [13]:
arr = np.array([10, 20, 30, 40, 50])

mask = arr % 20 == 0  # مقادیر مضرب ۲۰
print(arr[mask])  # خروجی → [20 40]

[20 40]


<div dir='rtl'>

🚀 **Masking در پردازش داده‌های یادگیری ماشین و هوش مصنوعی بسیار کاربردی است.**

---

### **🚀 نتیجه‌گیری**
**Indexing و Slicing در NumPy** به شما امکان می‌دهد که داده‌ها را به سرعت **انتخاب، پردازش و فیلتر** کنید، بدون نیاز به حلقه‌های کند Python.

---

### **🔹 تغییر شکل آرایه‌ها و عملیات پایه در NumPy**

در **NumPy**، امکان **تغییر شکل آرایه‌ها** بدون تغییر مقدار داده‌ها وجود دارد. این ویژگی در **پردازش داده‌ها، یادگیری ماشین و شبکه‌های عصبی** بسیار مهم است.

---

### **📌 ۱. `reshape()` – تغییر شکل آرایه**
🔹 **`reshape()`** ابعاد آرایه را تغییر می‌دهد.

</div>

In [14]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

reshaped = arr.reshape(2, 3)  # تبدیل آرایه 1D به 2D (۲×۳)
print(reshaped)

[[1 2 3]
 [4 5 6]]


<div dir='rtl'>

📌 باید تعداد عناصر **هماهنگ با شکل جدید** باشد.

---

### **📌 ۲. `ravel()` – تبدیل آرایه چندبعدی به یک‌بعدی**
🔹 **`ravel()`** آرایه را بدون تغییر مقدار، به **یک‌بعدی** تبدیل می‌کند.

</div>

In [15]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

flattened = arr.ravel()
print(flattened)

[1 2 3 4 5 6]


<div dir='rtl'>

📌 `ravel()` شبیه `reshape(-1)` است، اما آرایه **را تغییر نمی‌دهد**.

---

### **📌 ۳. `flatten()` – تبدیل آرایه چندبعدی به یک‌بعدی**
🔹 **`flatten()`** مشابه `ravel()` است، اما یک **کپی مستقل** از داده می‌سازد.

</div>

In [16]:
flat_arr = arr.flatten()
print(flat_arr)

[1 2 3 4 5 6]


<div dir='rtl'>

📌 تفاوت با `ravel()`: `flatten()` یک **کپی مستقل** ایجاد می‌کند، اما `ravel()` **اشاره‌ای به داده‌ی اصلی** دارد.

---

### **📌 ۴. `transpose()` – جابجایی سطر و ستون**
🔹 **`transpose()`** ماتریس را **برعکس** می‌کند:

</div>

In [17]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

transposed = arr.T  # معادل arr.transpose()
print(transposed)

[[1 4]
 [2 5]
 [3 6]]


<div dir='rtl'>

📌 استفاده در **شبکه‌های عصبی و پردازش تصویر** کاربرد زیادی دارد.

---

### **📌 ۵. تغییر تعداد ابعاد (`expand_dims`)**
🔹 با **`expand_dims()`** می‌توان به آرایه **یک بُعد اضافه کرد**.

</div>

In [18]:
arr = np.array([1, 2, 3])
expanded = np.expand_dims(arr, axis=0)  # تبدیل به ماتریس ۱×۳
print(expanded.shape)  # خروجی: (1, 3)

(1, 3)


<div dir='rtl'>

📌 **`axis=0`** → اضافه‌کردن ردیف  
📌 **`axis=1`** → اضافه‌کردن ستون  

---

### **🚀 نتیجه‌گیری**
با توابع **`reshape()`، `ravel()`، `transpose()` و `expand_dims()`** می‌توان **ساختار آرایه‌ها را مدیریت کرد** و برای **پردازش داده‌های هوش مصنوعی و یادگیری ماشین** آماده ساخت.

</div>