<div align="center">
  <img src="https://upload.wikimedia.org/wikipedia/commons/3/31/NumPy_logo_2020.svg" alt="لوگو" width="500">
</div>


<div dir='rtl'>

# آموزش کاربردی NUMPY با محوریت علوم داده و محاسبات عددی

## **جلسه سوم** عملیات عددی و برداری

### مدت زمان مطالعه  

مدت زمان مورد نیاز برای مطالعه این صفحه **20 تا 30 دقیقه** است. این مدت زمان بسته به سطح آشنایی شما با **Python** و موضوعات مرتبط ممکن است متغیر باشد.  


**تهیه‌کننده:** سجاد چمن‌آرا  

---

### **🔹 عملیات عددی روی آرایه‌های NumPy**

یکی از قابلیت‌های **اصلی** NumPy، انجام **محاسبات عددی سریع و بهینه** روی آرایه‌هاست. برخلاف لیست‌های معمولی Python، آرایه‌های NumPy می‌توانند عملیات ریاضی را بدون نیاز به حلقه‌ها و با **حداکثر سرعت** اجرا کنند.

### **🔹 انجام محاسبات عددی سریع و بهینه در NumPy**

یکی از مزایای **اصلی** NumPy، اجرای **محاسبات عددی بدون حلقه‌های کند `for`** است. این کتابخانه به شما امکان می‌دهد عملیات ریاضی را به‌صورت **برداری** انجام دهید، که به **سرعت و بهینه‌سازی مصرف حافظه** کمک می‌کند.

---

### **📌 ۱. جمع (`add`) و تفریق (`subtract`)**
🔹 جمع و تفریق مقدار ثابت یا دو آرایه به **صورت برداری**:

</div>

In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40])

print(np.add(arr, 5))  # افزودن ۵ به تمام عناصر → [15 25 35 45]
print(np.subtract(arr, 10))  # کاهش ۱۰ از هر مقدار → [0 10 20 30]

[15 25 35 45]
[ 0 10 20 30]


<div dir='rtl'; align='right'>

✅ **مزیت:** نیازی به حلقه‌های `for` نیست! NumPy عملیات را **بهینه** اجرا می‌کند.

---

### **📌 ۲. ضرب (`multiply`) و تقسیم (`divide`)**
🔹 ضرب و تقسیم مستقیم بر روی **تمام عناصر آرایه‌ها**:

</div>

In [2]:
print(np.multiply(arr, 2))  # ضرب هر مقدار در ۲ → [20 40 60 80]
print(np.divide(arr, 5))  # تقسیم هر مقدار بر ۵ → [2. 4. 6. 8.]

[20 40 60 80]
[2. 4. 6. 8.]


<div dir='rtl'; align='right'>

🚀 **بسیار سریع‌تر از روش‌های سنتی در Python!**

---

### **📌 ۳. محاسبات برداری روی دو آرایه**
🔹 اعمال عملیات روی **دو آرایه هم‌اندازه**:

</div>

In [3]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

print(np.add(arr1, arr2))  # جمع دو آرایه → [6 8 10 12]
print(np.multiply(arr1, arr2))  # ضرب عنصر به عنصر → [5 12 21 32]
print(np.divide(arr2, arr1))  # تقسیم عنصر به عنصر → [5.0 3.0 2.333 2.0]

[ 6  8 10 12]
[ 5 12 21 32]
[5.         3.         2.33333333 2.        ]


<div dir='rtl'; align='right'>

✅ **کاربرد مهم در شبکه‌های عصبی و پردازش تصویر!**

---

### **📌 ۴. انجام عملیات ریاضی پیشرفته**
🔹 می‌توان عملیات پیچیده را مستقیماً روی آرایه‌های NumPy اجرا کرد:

</div>

In [4]:
arr = np.array([1, 2, 3, 4])

print(np.power(arr, 2))  # توان دوم → [1 4 9 16]
print(np.sqrt(arr))  # جذر → [1. 1.41 1.73 2.]
print(np.log(arr))  # لگاریتم → [0. 0.69 1.09 1.38]

[ 1  4  9 16]
[1.         1.41421356 1.73205081 2.        ]
[0.         0.69314718 1.09861229 1.38629436]


<div dir='rtl'; align='right'>

📌 **NumPy بهینه‌ترین روش برای پردازش‌های ریاضی پیشرفته است!**

---

### **🚀 نتیجه‌گیری**
با استفاده از **محاسبات برداری، عملیات روی آرایه‌ها و پردازش عددی بهینه**، NumPy سرعت و کارایی پردازش داده‌ها را **چندین برابر** افزایش می‌دهد.

آیا مایلید درباره **عملیات برداری در شبکه‌های عصبی** بیشتر صحبت کنیم؟ 😊

---

</div>

<div dir='rtl'; align='right'>

### **🔹 محاسبات آماری در NumPy**

NumPy ابزارهای قدرتمندی برای انجام **محاسبات آماری** دارد که در تحلیل داده‌ها، یادگیری ماشین و بهینه‌سازی مدل‌ها بسیار **کاربردی** هستند. با استفاده از توابع NumPy، می‌توان داده‌ها را **به‌صورت برداری و بهینه** پردازش کرد.

---

### **📌 ۱. محاسبه میانگین (`mean`)**
🔹 **میانگین** یک مجموعه داده نشان‌دهنده مقدار **متوسط** آن است:

</div>

In [5]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

mean_value = np.mean(arr)
print(mean_value)  # خروجی: 30.0

30.0


<div dir='rtl'; align='right'>


📌 **کاربرد:** در **یادگیری ماشین** برای نرمال‌سازی داده‌ها استفاده می‌شود.

---

### **📌 ۲. محاسبه واریانس (`var`)**
🔹 **واریانس** میزان **پراکنده بودن داده‌ها** را نشان می‌دهد:

</div>

In [6]:
variance_value = np.var(arr)
print(variance_value)  # خروجی: 200.0

200.0


<div dir='rtl'; align='right'>


📌 **واریانس بالا** یعنی داده‌ها پراکندگی زیادی دارند.

---

### **📌 ۳. محاسبه انحراف معیار (`std`)**
🔹 **انحراف معیار** نشان‌دهنده میزان **تفاوت داده‌ها از میانگین** است:

</div>

In [7]:
std_value = np.std(arr)
print(std_value)  # خروجی: 14.14

14.142135623730951


<div dir='rtl'; align='right'>

📌 **در یادگیری ماشین** برای **معیارسازی داده‌ها** استفاده می‌شود.

---

### **📌 ۴. محاسبات آماری در ماتریس‌های چندبعدی**
🔹 محاسبه میانگین، واریانس و انحراف معیار برای **هر ستون یا هر ردیف**:

</div>

In [8]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])

print(np.mean(matrix, axis=0))  # میانگین هر ستون → [2.5 3.5 4.5]
print(np.var(matrix, axis=1))   # واریانس هر ردیف → [0.66 0.66]
print(np.std(matrix, axis=0))   # انحراف معیار هر ستون → [1.5 1.5 1.5]

[2.5 3.5 4.5]
[0.66666667 0.66666667]
[1.5 1.5 1.5]


<div dir='rtl'; align='right'>


🚀 **کاربردی در پردازش داده‌های چندبعدی و تحلیل آماری!**

---

### **🚀 نتیجه‌گیری**
با استفاده از **`mean`، `var` و `std`**، می‌توان داده‌ها را تحلیل کرد و اطلاعات **مهمی درباره پراکندگی و رفتار داده‌ها** به دست آورد.


</div>